[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/server"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
